[metadata]
name = sled
version = 0.1.4
author = Kevin Lane
author_email = kevin.lane@colorado.edu
description = A framework for Sclable Location Encoding via Distillation (SLED)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/geohai/sled
keywords = SLED, Remote Sensing, Huggingface
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: Apache Software License
    Operating System :: OS Independent

[options]
zip_safe = False
python_requires = >=3.10
install_requires = file: requirements.txt